[package]
name = "genominicus"
version = "0.4.2"
authors = ["Franklin Delehelle <delehelle@ens.fr>"]
edition = "2021"
license = "CECILL-2.1"
description = "A tool to plot gene trees"
repository = "https://github.com/delehef/genominicus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
askama = "0.16"
bimap = "0.6"
buche = "0.7.0"
clap = { version="4", features=["derive"] }
clap-verbosity-flag = "2.0.0"
colored = "2"
colorsys = "0.7"
either = "1.17"
enterpolation = { version = "0.3.0", default-features = false, features = ["linear", "std"] }
flate2 = "1.1"
itertools = "0.15"
log = "0.4"
maplit = "1"
md5 = "0.8"
newick = "0.12"
# newick = { path = "../newick" }
open = "5"
palette = "0.7"
petgraph = "0.8"
petname = "3"
rand = "0.10"
ratatui = "0.30"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
svarog = "0.6"
syntesuite = "0.7"
thiserror = "2"
tui-textarea-2 = "0.12"

[package.metadata.release]
tag-prefix = ""
publish = false
pre-release-hook = ["git-cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
allow-branch = ["master"]
