[package]
name = "genominicus"
version = "0.1.0"
authors = ["Franklin Delehelle <franklin.delehelle@odena.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
pest = "2"
pest_derive = "2"
smartstring = "0.2"
